#use_frameworks!

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'YLBNetwork_Example' do
  pod 'YLBNetwork', :path => '../'

  target 'YLBNetwork_Tests' do
    inherit! :search_paths

    
  end
end
